#ifndef CREATURES_COMMON_H
#define CREATURES_COMMON_H

#include "ghidra_types.h"
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#define REMOVE_MAX_PATH 260

#define CREATURES_DIRECTORY_SLOT_COUNT 8
#define CREATURES_DIRECTORY_VALUE_SIZE 128

#define CREATURES_BODY_PAIR_ROWS 10
#define CREATURES_BODY_PAIR_COLUMNS 6
#define CREATURES_BODY_QUAD_ROWS 10

#define CREATURES_WORLD_WRAP_WIDTH 0x20a0
#define CREATURES_BODY_CHAIN_COUNT 6

#define CREATURES_BODY_SLOT_COUNT 14
#define CREATURES_BODY_BASE_SLOT_COUNT 12

#define CREATURES_GENE_MAGIC 0x656e6567u
#define CREATURES_GENE_END_MAGIC 0x646e6567u

#define CREATURES_SPRITE_FILE_CACHE_SLOT_COUNT 10
#define CREATURES_GENOME_STATE_SIZE 28

#define CREATURES_WAIT_BEHAVIOR_PRIMARY_SCRIPT_COUNT 16
#define CREATURES_WAIT_BEHAVIOR_AUXILIARY_SCRIPT_COUNT 3
#define CREATURES_BEHAVIOR_SCRIPT_TEXT_CAPACITY 0x32
#define CREATURES_MAX_BODY_VARIANT_STAGE 7
#define CREATURES_IMPORTED_CREATURE_WORLD_X 0x0a1f
#define CREATURES_IMPORTED_CREATURE_WORLD_Y 0x039f

typedef int (*CreaturesRandomProc)(void *ctx);

#endif
